address = "0.0.0.0:50051"
queue = ["https://en.wikipedia.org/wiki/C_(programming_language)", "https://en.wikipedia.org/wiki/Rust_(programming_language)"]
barrels = ["127.0.0.1:50052", "192.168.41.123:6464"]
[domains_filter]
whitelist = ["good.com"]
blacklist = ["bad.com"]
